import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.WebDriverWait;

import static org.openqa.selenium.support.ui.ExpectedConditions.presenceOfElementLocated;

public class visa {
    private WebDriver driver;
    private WebDriverWait wait;
    String[] Names = {
            "Васька",
            "Кузя",
            "Барсик",
            "Мурзик",
            "Леопольд",
            "Бегемот",
            "Рыжик",
            "Матрdasdasdоскин",
            "adasdasd",
            "asdaasdasdsad",
            "2341243234",
            "asdadassda",
            "Вsadаська",
            "Кузя",
            "Барсик",
            "Мурasdasdзик",
            "Леопольд",
            "Бегемот",
            "Рыжик",
            "Матрasdasdоскин",
            "adasdasd",
            "asdsdasdasdasdadsad",
            "2341243234",
            "asddsadasda",
            "Васька",
            "Кузя",
            "Барсик",
            "Мурзик",
            "Леопольд",
            "2342егемот",
            "Рыжик",
            "Ма342342трdasdasdоскин",
            "adasdasd",
            "asdaasdasdsad",
            "2341243234",
            "asd2342adassda",
            "Вsadаська",
            "Ку34234зя",
            "Бар234сик",
            "Му23423рasdasdзик",
            "Леопольд",
            "Бег4234емот",
            "Рыж23423ик",
            "Матр34234asdasdоскин",
            "adasd2342asd",
            "asdsd234234asdasdasdadsad",
            "2341243234",
            "asdds234adasda",
            "Васька",
            "Кузя",
            "Барсик",
            "Мурзик",
            "Леопольд",
            "Бегемот",
            "Рыжик",
            "Матрdasdasdоскин",
            "adasdasd",
            "asdaasdasdsad",
            "2341243234",
            "asdadassda",
            "Вsadаська",
            "Кузя",
            "Барсик",
            "Мурasdasdзик",
            "Леопольд",
            "Бегемот",
            "Рыжик",
            "Матрasdasdоскин",
            "adasdasd",
            "asdswerwdasdasdasdadsad",
            "2wer341243234",
            "asddsadasda",
            "wer",
            "Куeerwerwзя",
            "Баwerwрсик",
            "Мурwerзик",
            "Леweпольд",
            "2342егемот",
            "Рыжw34erик",
            "Ма344234wer2342трdasdasdоскин",
            "adwrwerwerasdasd",
            "423423",
            "2341er243234",
            "asd2werw342adassda",
            "Вsadr2342342аська",
            "Ку34erw234зя",
            "Бар234сик",
            "Му2ewerwwrwerwer3423рasdasdзик",
            "Леопerольд",
            "Бег4r234емот",
            "Рыж2rw3423ик",
            "Мат234234рwerw34234asdasdоскин",
            "ada234234serwerwed2342asd",
            "asd34234234sd234234asdasdasdadsad",
            "234werw1243234",
            "asdd23423erwerws234adasda",
            "Васька",
            "Куз42342я",
            "Барсик",
            "Мурзик",
            "Леопольд",
            "Бег4234234емот",
            "Ры22342334жик",
            "Матр34234dasdasdоскин",
            "adasdasd",
            "asd3423aasdasdsad",
            "234423421243234",
            "asdadassda",
            "Вsadаська",
            "Ку23423зя",
            "Бар42342342сик",
            "Мурasdasdзик",
            "Лео234234234234польд",
            "Бег234емот",
            "Рыжи34234234к",
            "Матрasdasdоскин",
            "adasdasd",
            "asdsdasdasdasdadsad",
            "2341243234",
            "asddsadasda",
            "Васsdasdька",
            "Кузs234343242342342я",
            "Баsadadрdasdaсик",
            "Мурзик",
            "Леопольд",
            "2342егемот",
            "Рыжик",
            "Ма342342трdasdasdоскин",
            "adasdasd",
            "asdaasdasdsad",
            "2341sdasda243234",
            "asd2342adassda",
            "Вsasdasdaadаська",
            "Ку34234зя",
            "Бар234сик",
            "Му2asdasd3423рasdasdзик",
            "Леопольд",
            "Бег4234емот",
            "Рыж23423ик",
            "Матр34234asdasdоскин",
            "уйцу",
            "asdsd234234asdasdasdadsad",
            "йцу",
            "aйцуsdds234adasda",
            "Вайцуйцуська",
            "Куцйуйцузя",
            "Барсик",
            "Муцуйцурзик",
            "Лейцуйопольд",
            "Бецуйцуйцугемот",
            "Рыжик",
            "Матйцуйрdasdasdоскин",
            "adasdasd",
            "asdaasdasdsad",
            "2341йцуйццу243234",
            "asdadassda",
            "Вsaйцуйцуdаська",
            "Кузя",
            "Барсик",
            "Мурasdaйцуйуйцуsdзик",
            "Леопольд",
            "Бегемот",
            "Рыжик",
            "Матрasdasdоскин",
            "adasdasd",
            "asdswerwdasdasdasdadsad",
            "2wer3цйцуйцуйцу41243234",
            "asdйуцйуйцуйуdsadasda",
            "wer",
            "Куeerwerwзя",
            "Баwerwцуйцуруйцуйсик",
            "Мурwerзик",
            "Леweпольд",
            "2342егемот",
            "Рыжwerик",
            "Ма34wer2342трdasdasdоскин",
            "adwrwцуйццуйerwerasdasd",
            "asdaarsdasdsad",
            "2341er243234",
            "asd2werw342adassda",
            "Вsadrаська",
            "Ку34erw234зя",
            "Барй234сик",
            "Му2ewerwwrwerwer3423рasdasdзик",
            "Леопerольд",
            "Бегйцуй4r234емот",
            "Рыж2rw3423ик",
            "Матрwerw34234asdasdоскин",
            "adйцуйуцaserwerwed2342asd",
            "asdsd234234asdasdasdadsad",
            "234werw1243234",
            "asdderwerws234adasda",

    };


    @Before
    public void start() {
        driver = new ChromeDriver();
        wait = new WebDriverWait(driver, 10);
        driver.manage().window().maximize();
    }

           @Test
        public void Visa () {

        driver.get("http://visa.index-inner.me/test");
        wait.until(presenceOfElementLocated(By.id("test")));
        for (int i=0; i<Names.length; i++) {
            driver.findElement(By.id("test")).sendKeys(Names[i]);
            driver.findElement(By.xpath("//button[@class='btn btn-success']")).click();
            driver.findElement(By.id("test")).click();
            driver.findElement(By.id("test")).clear();
        }
    }

    @After
    public void stop() {
        // driver.quit();
        driver = null;
    }
}
